import camelcaseKeys from 'camelcase-keys';

export const mockMarineTrims = [
  {
    text: 'BF115',
    value: '12075',
    name: 'BF115',
    detIdentifier: '12075',
    model: 'BF115',
    modelPage: {
      name: 'bf115',
      url: '/en/drive-by-wire/bf115',
    },
    thumbnail: {
      src: 'https://marine-uat-01-dmm.marine.honda.ca/-/media/Brands/Marine/Category-Landing-Page/Studio---Desktop/DBW/115_206x334_25.png?h=334&iar=0&w=206&rev=34652d22b7854011a7e724caf5fe493e&hash=672A50785D5048419122F147D00996E0',
      alt: 'Side view of a BF115',
      width: '206',
      height: '334',
      url: 'https://marine-uat-01-dmm.marine.honda.ca/-/media/Brands/Marine/Category-Landing-Page/Studio---Desktop/DBW/115_206x334_25.png?h=334&iar=0&w=206&rev=34652d22b7854011a7e724caf5fe493e&hash=672A50785D5048419122F147D00996E0',
    },
  },
  {
    text: 'BF150',
    value: '12022',
    name: 'BF150',
    detIdentifier: '12022',
    model: 'BF150',
    modelPage: {
      name: 'bf150',
      url: '/en/large-motors/bf150',
    },
    thumbnail: {
      src: 'https://marine-uat-01-dmm.marine.honda.ca/-/media/Brands/Marine/Category-Landing-Page/Studio---Desktop/Large/150_206x334_25.png?h=334&iar=0&w=206&rev=988a9c4d249e426b917ef1ae5479cb0b&hash=88B94C29835A51529F598682CDEB44D4',
      alt: 'Side view of a BF150',
      width: '206',
      height: '334',
      url: 'https://marine-uat-01-dmm.marine.honda.ca/-/media/Brands/Marine/Category-Landing-Page/Studio---Desktop/Large/150_206x334_25.png?h=334&iar=0&w=206&rev=988a9c4d249e426b917ef1ae5479cb0b&hash=88B94C29835A51529F598682CDEB44D4',
    },
  },
  null,
  null,
];

const marineSpecs = [
  {
    TrimId: 12022,
    DisplayOrder: 1,
    Label: 'ENGINE',
    Name: 'engine',
    Specs: [
      {
        DisplayOrder: 1,
        Label: 'Type',
        Name: 'type',
        Tip: '',
        Value: '4-Stroke DOHC, VTEC; 4 Cylinder / 16 Valves',
      },
      {
        DisplayOrder: 2,
        Label: 'Displacement',
        Name: 'displacement',
        Tip: '',
        Value: '2, 354 cc / 144 cubic in.',
      },
      {
        DisplayOrder: 3,
        Label: 'Bore & Stroke',
        Name: 'bore___stroke',
        Tip: '',
        Value: '87 x 99 mm (3.43 x 3.89 in.)',
      },
      {
        DisplayOrder: 4,
        Label: 'Full Throttle RPM Range',
        Name: 'full_throttle_rpm_range',
        Tip: '',
        Value: '5,000-6,000 RPM',
      },
      {
        DisplayOrder: 5,
        Label: 'Propshaft Rated Horsepower (HP)',
        Name: 'propshaft_rated_horsepower__hp_',
        Tip: '',
        Value: '150 hp @ 5,500 RPM',
      },
      {
        DisplayOrder: 6,
        Label: 'Cooling System',
        Name: 'cooling_system',
        Tip: '',
        Value: 'Water Cooled',
      },
      {
        DisplayOrder: 7,
        Label: 'Fuel Delivery',
        Name: 'fuel_delivery',
        Tip: '',
        Value: 'Programmed Electronic Fuel Injection (PGM-FI)',
      },
      {
        DisplayOrder: 8,
        Label: 'Recommended Fuel',
        Name: 'recommended_fuel',
        Tip: '',
        Value: 'Unleaded Gas. (Min. Pump Octane 86)',
      },
      {
        DisplayOrder: 9,
        Label: 'Ignition System',
        Name: 'ignition_system',
        Tip: '',
        Value: 'MicroComputer Programmed',
      },
      {
        DisplayOrder: 10,
        Label: 'Starting System',
        Name: 'starting_system',
        Tip: '',
        Value: 'Electric',
      },
      {
        DisplayOrder: 11,
        Label: 'Exhaust',
        Name: 'exhaust',
        Tip: '',
        Value: 'Through Prop Hub',
      },
      {
        DisplayOrder: 12,
        Label: 'Lubrication',
        Name: 'lubrication',
        Tip: '',
        Value: 'Wet Sump',
      },
      {
        DisplayOrder: 13,
        Label: 'Recommended Oil',
        Name: 'recommended_oil',
        Tip: '',
        Value: 'Honda 10W30 FC-W™ outboard motor oil',
      },
      {
        DisplayOrder: 14,
        Label: 'Oil Capacity',
        Name: 'oil_capacity',
        Tip: '',
        Value: '6.70 L (5.90 Imp. qt) with oil filter repl.',
      },
      {
        DisplayOrder: 15,
        Label: 'Trim Range',
        Name: 'trim_range',
        Tip: '',
        Value: '-4° to +16°',
      },
      {
        DisplayOrder: 16,
        Label: 'Tilt Range',
        Name: 'tilt_range',
        Tip: '',
        Value: '72°',
      },
      {
        DisplayOrder: 17,
        Label: 'Steering Angle',
        Name: 'steering_angle',
        Tip: '',
        Value: '30°',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 1,
    Label: 'ENGINE',
    Name: 'engine',
    Specs: [
      {
        DisplayOrder: 1,
        Label: 'Type',
        Name: 'type',
        Tip: '',
        Value: '4-Stroke DOHC; 4 Cylinder / 16 Valves',
      },
      {
        DisplayOrder: 2,
        Label: 'Displacement',
        Name: 'displacement',
        Tip: '',
        Value: '2,354 cc / 144 cubic in.',
      },
      {
        DisplayOrder: 3,
        Label: 'Bore & Stroke',
        Name: 'bore___stroke',
        Tip: '',
        Value: '87 x 99 mm (3.43 x 3.89 in.)',
      },
      {
        DisplayOrder: 4,
        Label: 'Full Throttle RPM Range',
        Name: 'full_throttle_rpm_range',
        Tip: '',
        Value: '4,500-6,000 RPM',
      },
      {
        DisplayOrder: 5,
        Label: 'Propshaft Rated Horsepower (HP)',
        Name: 'propshaft_rated_horsepower__hp_',
        Tip: '',
        Value: '115 hp @ 5,250 RPM',
      },
      {
        DisplayOrder: 6,
        Label: 'Cooling System',
        Name: 'cooling_system',
        Tip: '',
        Value: 'Water Cooled',
      },
      {
        DisplayOrder: 7,
        Label: 'Fuel Delivery',
        Name: 'fuel_delivery',
        Tip: '',
        Value: 'Programmed Electronic Fuel Injection (PGM-FI)',
      },
      {
        DisplayOrder: 8,
        Label: 'Recommended Fuel',
        Name: 'recommended_fuel',
        Tip: '',
        Value: 'Unleaded Gas. (Min. Pump Octane 86)',
      },
      {
        DisplayOrder: 9,
        Label: 'Ignition System',
        Name: 'ignition_system',
        Tip: '',
        Value: 'MicroComputer Programmed',
      },
      {
        DisplayOrder: 10,
        Label: 'Starting System',
        Name: 'starting_system',
        Tip: '',
        Value: 'Electric',
      },
      {
        DisplayOrder: 11,
        Label: 'Exhaust',
        Name: 'exhaust',
        Tip: '',
        Value: 'Through Prop Hub',
      },
      {
        DisplayOrder: 12,
        Label: 'Lubrication',
        Name: 'lubrication',
        Tip: '',
        Value: 'Wet Sump',
      },
      {
        DisplayOrder: 13,
        Label: 'Recommended Oil',
        Name: 'recommended_oil',
        Tip: '',
        Value: 'Honda 10W30 FC-W<sup>™</sup> outboard motor oil',
      },
      {
        DisplayOrder: 14,
        Label: 'Oil Capacity',
        Name: 'oil_capacity',
        Tip: '',
        Value: '6.70 L (5.90 Imp. qt) with oil filter repl.',
      },
      {
        DisplayOrder: 15,
        Label: 'Trim Range',
        Name: 'trim_range',
        Tip: '',
        Value: '-4° to +16°',
      },
      {
        DisplayOrder: 16,
        Label: 'Tilt Range',
        Name: 'tilt_range',
        Tip: '',
        Value: '68°',
      },
      {
        DisplayOrder: 17,
        Label: 'Steering Angle',
        Name: 'steering_angle',
        Tip: '',
        Value: '30°',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 2,
    Label: 'DRIVE',
    Name: 'drive',
    Specs: [
      {
        DisplayOrder: 18,
        Label: 'Gear Ratio',
        Name: 'gear_ratio',
        Tip: '',
        Value: '2.14:1',
      },
      {
        DisplayOrder: 19,
        Label: 'Gear Shift',
        Name: 'gear_shift',
        Tip: '',
        Value: 'F-N-R',
      },
    ],
  },
  {
    TrimId: 12022,
    DisplayOrder: 2,
    Label: 'DRIVE',
    Name: 'drive',
    Specs: [
      {
        DisplayOrder: 18,
        Label: 'Gear Ratio',
        Name: 'gear_ratio',
        Tip: '',
        Value: '2.14:1',
      },
      {
        DisplayOrder: 19,
        Label: 'Gear Shift',
        Name: 'gear_shift',
        Tip: '',
        Value: 'F-N-R',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 3,
    Label: 'EQUIPMENT',
    Name: 'equipment',
    Specs: [
      {
        DisplayOrder: 20,
        Label: 'Alternator (Manual Start)',
        Name: 'alternator__manual_start_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 21,
        Label: 'Alternator (Electric Start)',
        Name: 'alternator__electric_start_',
        Tip: '',
        Value: '55 amp',
      },
      {
        DisplayOrder: 22,
        Label: 'Battery Charging Power',
        Name: 'battery_charging_power',
        Tip: '',
        Value: '40 amp',
      },
      {
        DisplayOrder: 23,
        Label: 'Power Tilt',
        Name: 'power_tilt',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 24,
        Label: 'Power Trim & Tilt',
        Name: 'power_trim___tilt',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 25,
        Label: 'Gas Assisted Tilt',
        Name: 'gas_assisted_tilt',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 26,
        Label: 'Oil Pressure Alert',
        Name: 'oil_pressure_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 27,
        Label: 'Over Rev-Limiter',
        Name: 'over_rev_limiter',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 28,
        Label: 'Temperature Alert',
        Name: 'temperature_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 29,
        Label: 'Water in Fuel Alert',
        Name: 'water_in_fuel_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 30,
        Label: 'Battery Condition Alert',
        Name: 'battery_condition_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 31,
        Label: 'Speedometer Pickup',
        Name: 'speedometer_pickup',
        Tip: '',
        Value: 'Standard*',
      },
      {
        DisplayOrder: 32,
        Label: 'Variable Speed Trolling Kit',
        Name: 'variable_speed_trolling_kit',
        Tip: '',
        Value: 'Optional',
      },
      {
        DisplayOrder: 33,
        Label: 'Rudder Meter Kit',
        Name: 'rudder_meter_kit',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 34,
        Label: 'Tilt limiter switch',
        Name: 'tilt_limiter_switch',
        Tip: 'Correction in green',
        Value: 'Standard',
      },
    ],
  },
  {
    TrimId: 12022,
    DisplayOrder: 3,
    Label: 'EQUIPMENT',
    Name: 'equipment',
    Specs: [
      {
        DisplayOrder: 20,
        Label: 'Alternator (Manual Start)',
        Name: 'alternator__manual_start_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 21,
        Label: 'Alternator (Electric Start)',
        Name: 'alternator__electric_start_',
        Tip: '',
        Value: '51 amp',
      },
      {
        DisplayOrder: 22,
        Label: 'Battery Charging Power',
        Name: 'battery_charging_power',
        Tip: '',
        Value: '30 amp @1,000 RPM; 40 amp @2,000+ RPM',
      },
      {
        DisplayOrder: 23,
        Label: 'Power Tilt',
        Name: 'power_tilt',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 24,
        Label: 'Power Trim & Tilt',
        Name: 'power_trim___tilt',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 25,
        Label: 'Gas Assisted Tilt',
        Name: 'gas_assisted_tilt',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 26,
        Label: 'Oil Pressure Alert',
        Name: 'oil_pressure_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 27,
        Label: 'Over Rev-Limiter',
        Name: 'over_rev_limiter',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 28,
        Label: 'Temperature Alert',
        Name: 'temperature_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 29,
        Label: 'Water in Fuel Alert',
        Name: 'water_in_fuel_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 30,
        Label: 'Battery Condition Alert',
        Name: 'battery_condition_alert',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 31,
        Label: 'Speedometer Pickup',
        Name: 'speedometer_pickup',
        Tip: '',
        Value: 'Standard',
      },
      {
        DisplayOrder: 32,
        Label: 'Variable Speed Trolling Kit',
        Name: 'variable_speed_trolling_kit',
        Tip: '',
        Value: 'Optional',
      },
      {
        DisplayOrder: 33,
        Label: 'Rudder Meter Kit',
        Name: 'rudder_meter_kit',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 34,
        Label: 'Tilt limiter switch',
        Name: 'tilt_limiter_switch',
        Tip: 'Correction in green',
        Value: 'Standard',
      },
    ],
  },
  {
    TrimId: 12022,
    DisplayOrder: 4,
    Label: 'DIMENSIONS',
    Name: 'dimensions',
    Specs: [
      {
        DisplayOrder: 35,
        Label: 'Overall Width',
        Name: 'overall_width',
        Tip: 'Correction in green',
        Value: '610 mm/24 in.',
      },
      {
        DisplayOrder: 36,
        Label: 'Transom Height (S-Type)',
        Name: 'transom_height__s_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 37,
        Label: 'Transom Height (SCHC-Type)',
        Name: 'transom_height__schc_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 38,
        Label: 'Transom Height (L-Type)',
        Name: 'transom_height__l_type_',
        Tip: '',
        Value: '508 mm / 20 in.',
      },
      {
        DisplayOrder: 39,
        Label: 'Transom Height (LCHC-Type)',
        Name: 'transom_height__lchc_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 40,
        Label: 'Transom Height (X-Type)',
        Name: 'transom_height__x_type_',
        Tip: '',
        Value: '635 mm / 25 in.',
      },
      {
        DisplayOrder: 41,
        Label: 'Transom Height (XX-Type)',
        Name: 'transom_height__xx_type_',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 4,
    Label: 'DIMENSIONS',
    Name: 'dimensions',
    Specs: [
      {
        DisplayOrder: 35,
        Label: 'Overall Width',
        Name: 'overall_width',
        Tip: 'Correction in green',
        Value: '610 mm/24 in.',
      },
      {
        DisplayOrder: 36,
        Label: 'Transom Height (S-Type)',
        Name: 'transom_height__s_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 37,
        Label: 'Transom Height (SCHC-Type)',
        Name: 'transom_height__schc_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 38,
        Label: 'Transom Height (L-Type)',
        Name: 'transom_height__l_type_',
        Tip: '',
        Value: '508 mm / 20 in.',
      },
      {
        DisplayOrder: 39,
        Label: 'Transom Height (LCHC-Type)',
        Name: 'transom_height__lchc_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 40,
        Label: 'Transom Height (X-Type)',
        Name: 'transom_height__x_type_',
        Tip: '',
        Value: '635 mm / 25 in.',
      },
      {
        DisplayOrder: 41,
        Label: 'Transom Height (XX-Type)',
        Name: 'transom_height__xx_type_',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 5,
    Label: 'PROPELLER',
    Name: 'propeller',
    Specs: [
      {
        DisplayOrder: 42,
        Label: 'Propeller Type',
        Name: 'propeller_type',
        Tip: '',
        Value: 'Optional',
      },
      {
        DisplayOrder: 43,
        Label: 'Propeller Diameter x Pitch (S-Type)',
        Name: 'propeller_diameter_x_pitch__s_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 44,
        Label: 'Propeller Diameter x Pitch (L-Type)',
        Name: 'propeller_diameter_x_pitch__l_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 45,
        Label: 'Propeller Diameter x Pitch (BF(P) Models)',
        Name: 'propeller_diameter_x_pitch__bf_p__models_',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
  {
    TrimId: 12022,
    DisplayOrder: 5,
    Label: 'PROPELLER',
    Name: 'propeller',
    Specs: [
      {
        DisplayOrder: 42,
        Label: 'Propeller Type',
        Name: 'propeller_type',
        Tip: '',
        Value: 'Optional',
      },
      {
        DisplayOrder: 43,
        Label: 'Propeller Diameter x Pitch (S-Type)',
        Name: 'propeller_diameter_x_pitch__s_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 44,
        Label: 'Propeller Diameter x Pitch (L-Type)',
        Name: 'propeller_diameter_x_pitch__l_type_',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 45,
        Label: 'Propeller Diameter x Pitch (BF(P) Models)',
        Name: 'propeller_diameter_x_pitch__bf_p__models_',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
  {
    TrimId: 12075,
    DisplayOrder: 6,
    Label: 'DRY WEIGHT',
    Name: 'dry_weight',
    Specs: [
      {
        DisplayOrder: 46,
        Label: 'S-Type',
        Name: 's_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 47,
        Label: 'SCHC-Type',
        Name: 'schc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 48,
        Label: 'SHGC-Type',
        Name: 'shgc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 49,
        Label: 'SHS-Type',
        Name: 'shs_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 50,
        Label: 'SRC-Type',
        Name: 'src_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 51,
        Label: 'L-Type',
        Name: 'l_type',
        Tip: 'Correction in green',
        Value: '218 kg/480 lb.(mech); \n221kg/487lb. (iST)',
      },
      {
        DisplayOrder: 52,
        Label: 'LCHC-Type',
        Name: 'lchc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 53,
        Label: 'LHGC-Type',
        Name: 'lhgc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 54,
        Label: 'LRTC-Type',
        Name: 'lrtc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 55,
        Label: 'X-Type',
        Name: 'x_type',
        Tip: 'Correction in green',
        Value: '221 kg/487 lb. (mech); \n224kg/493 lb. (iST)',
      },
      {
        DisplayOrder: 56,
        Label: 'XC-Type',
        Name: 'xc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 57,
        Label: 'XRTC-Type',
        Name: 'xrtc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 58,
        Label: 'XX-Type',
        Name: 'xx_type',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
  {
    TrimId: 12022,
    DisplayOrder: 6,
    Label: 'DRY WEIGHT',
    Name: 'dry_weight',
    Specs: [
      {
        DisplayOrder: 46,
        Label: 'S-Type',
        Name: 's_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 47,
        Label: 'SCHC-Type',
        Name: 'schc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 48,
        Label: 'SHGC-Type',
        Name: 'shgc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 49,
        Label: 'SHS-Type',
        Name: 'shs_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 50,
        Label: 'SRC-Type',
        Name: 'src_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 51,
        Label: 'L-Type',
        Name: 'l_type',
        Tip: 'Not in lineup',
        Value: '217 kg / 478 lbs (With propeller mounted)',
      },
      {
        DisplayOrder: 52,
        Label: 'LCHC-Type',
        Name: 'lchc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 53,
        Label: 'LHGC-Type',
        Name: 'lhgc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 54,
        Label: 'LRTC-Type',
        Name: 'lrtc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 55,
        Label: 'X-Type',
        Name: 'x_type',
        Tip: 'Correction in green',
        Value: '221 kg/487 lb. (mech); \n224 kg/493 lb. (iST)',
      },
      {
        DisplayOrder: 56,
        Label: 'XC-Type',
        Name: 'xc_type',
        Tip: 'Correction in green',
        Value: '224 kg/494 lb. (mech); \n227 kg/500lb. (iST)',
      },
      {
        DisplayOrder: 57,
        Label: 'XRTC Type',
        Name: 'xrtc_type',
        Tip: '',
        Value: 'N/A',
      },
      {
        DisplayOrder: 58,
        Label: 'XX Type',
        Name: 'xx_type',
        Tip: '',
        Value: 'N/A',
      },
    ],
  },
];

export const mockMarineSpecs = camelcaseKeys(marineSpecs, { deep: true });
