export default [
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73876_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73876_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73876_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73876_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '13908_cargo_organizer',
    AccessoryCategory: {
      DisplayOrder: 108,
      Key: 'interior',
      Name: 'Interior',
      GtmName: 'Interior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'The Cargo Organizer offers an ideal way to help keep easily spillable items upright in the back section of your MDX.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.1,
    AccessoryId: 13908,
    AccessoryIsResidualized: false,
    AccessoryKey: 'cargo_organizer',
    AccessoryListPrice: 129.0,
    AccessoryName: 'Cargo Organizer',
    AccessoryGtmName: 'Cargo Organizer',
    AccessoryNumber: '08U20-STK-200',
    AccessoryProvincialPrice: 145.3,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 7,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73848_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73848_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73848_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73848_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '13957_crossbars_storage_bag',
    AccessoryCategory: {
      DisplayOrder: 109,
      Key: 'exterior',
      Name: 'Exterior',
      GtmName: 'Exterior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: 'Conveniently store your crossbars in this handy storage bag when not in use.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 13957,
    AccessoryIsResidualized: false,
    AccessoryKey: 'crossbars_storage_bag',
    AccessoryListPrice: 145.0,
    AccessoryName: 'Crossbars - Storage Bag',
    AccessoryGtmName: 'Crossbars - Storage Bag',
    AccessoryNumber: '08U51-TJB-200',
    AccessoryProvincialPrice: 145.0,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 41,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73845_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73845_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73845_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73845_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '13961_roof_rack__fork_mount_bike_attachment',
    AccessoryCategory: {
      DisplayOrder: 109,
      Key: 'exterior',
      Name: 'Exterior',
      GtmName: 'Exterior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'The Fork Mount Bike Attachment features a same side adjustment dial that provides fast loading and maximum security for your bike.  Requires Roof Rails and Crossbars.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.4,
    AccessoryId: 13961,
    AccessoryIsResidualized: false,
    AccessoryKey: 'roof_rack__fork_mount_bike_attachment',
    AccessoryListPrice: 403.0,
    AccessoryName: 'Bike Attachment - Fork Mount',
    AccessoryGtmName: 'Bike Attachment - Fork Mount',
    AccessoryNumber: '08L07-E09-400A',
    AccessoryProvincialPrice: 468.2,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 14,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73885_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73885_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73885_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73885_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14001_optimate_12v_auto_battery_charger_maintainer',
    AccessoryCategory: {
      DisplayOrder: 109,
      Key: 'exterior',
      Name: 'Exterior',
      GtmName: 'Exterior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: 'Extended battery life by charging/maintaining an Acura battery to ideal charge levels.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 14001,
    AccessoryIsResidualized: false,
    AccessoryKey: 'optimate_12v_auto_battery_charger_maintainer',
    AccessoryListPrice: 133.0,
    AccessoryName: 'OPTIMATE 12V AUTO BATTERY CHARGER/MAINTAINER',
    AccessoryGtmName: 'OPTIMATE 12V AUTO BATTERY CHARGER/MAINTAINER',
    AccessoryNumber: '31670-BMS-004A',
    AccessoryProvincialPrice: 133.0,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 50,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73838_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73838_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73838_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73838_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14119_cold_protection_package',
    AccessoryCategory: {
      DisplayOrder: 105,
      Key: 'packages',
      Name: 'Packages',
      GtmName: 'Packages',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: ' Package includes: Engine Block Heater and Optimate 12V Auto Battery Charger/Maintainer.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 2.0,
    AccessoryId: 14119,
    AccessoryIsResidualized: true,
    AccessoryKey: 'cold_protection_package',
    AccessoryListPrice: 283.0,
    AccessoryName: 'COLD WEATHER PACKAGE - 3.5L',
    AccessoryGtmName: 'COLD WEATHER PACKAGE - 3.5L',
    AccessoryNumber: '22MDX-CLD-PKG',
    AccessoryProvincialPrice: 609.0,
    AccessoryResidualAmount: 500.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 3,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73839_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73839_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73839_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73839_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14120_launch_package_a___mdx',
    AccessoryCategory: {
      DisplayOrder: 105,
      Key: 'packages',
      Name: 'Packages',
      GtmName: 'Packages',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Package includes: Cargo Cover, Illuminated Door Sill Trims (ACURA), and Running Boards with Attachments in Chrome.',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 3.0,
    AccessoryId: 14120,
    AccessoryIsResidualized: false,
    AccessoryKey: 'launch_package_a___mdx',
    AccessoryListPrice: 2362.0,
    AccessoryName: 'Enhanced Package - MDX',
    AccessoryGtmName: 'Enhanced Package - MDX',
    AccessoryNumber: '22MDX-ENH-PKG1',
    AccessoryProvincialPrice: 2851.0,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 6,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73840_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73840_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73840_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73840_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14123_protection_package_a___mdx',
    AccessoryCategory: {
      DisplayOrder: 105,
      Key: 'packages',
      Name: 'Packages',
      GtmName: 'Packages',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: ' Package includes: 1st, 2nd, and 3rd Row All-Season Floor Mats and Folding Cargo Tray.',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.3,
    AccessoryId: 14123,
    AccessoryIsResidualized: false,
    AccessoryKey: 'protection_package_a___mdx',
    AccessoryListPrice: 659.0,
    AccessoryName: 'Protection Package - MDX (Out of Stock)',
    AccessoryGtmName: 'Protection Package - MDX (Out of Stock)',
    AccessoryNumber: '22MDX-PRO-PKG1',
    AccessoryProvincialPrice: 707.9,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 9,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73872_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73872_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73872_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73872_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14154_all_season_floor_mat__high_wall___mdx',
    AccessoryCategory: {
      DisplayOrder: 108,
      Key: 'interior',
      Name: 'Interior',
      GtmName: 'Interior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      ' An ideal way to save wear and tear on your original carpets, the All-Season Floor Mats are designed to trap and hold dirt, sand, mud and water.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.1,
    AccessoryId: 14154,
    AccessoryIsResidualized: false,
    AccessoryKey: 'all_season_floor_mat__high_wall___mdx',
    AccessoryListPrice: 309.0,
    AccessoryName: 'All-Season Floor Mats, MDX - 1st & 2nd Row (Out of Stock)',
    AccessoryGtmName: 'All-Season Floor Mats, MDX - 1st & 2nd Row (Out of Stock)',
    AccessoryNumber: '08P17-TYA-210',
    AccessoryProvincialPrice: 325.3,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 1,
  },
  {
    TransmissionId: 10280,
    OverlayAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73873_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73873_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://images.honda.ca:443/accessories/A/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73873_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://images.honda.ca:443/accessories/A/2024/73873_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '14156_all_season_floor_mat__high_wall___3rd_row',
    AccessoryCategory: {
      DisplayOrder: 108,
      Key: 'interior',
      Name: 'Interior',
      GtmName: 'Interior',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      ' An ideal way to save wear and tear on your original carpets, the All-Season Floor Mats are designed to trap and hold dirt, sand, mud and water.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.1,
    AccessoryId: 14156,
    AccessoryIsResidualized: false,
    AccessoryKey: 'all_season_floor_mat__high_wall___3rd_row',
    AccessoryListPrice: 122.0,
    AccessoryName: 'All-Season Floor Mat - 3rd Row',
    AccessoryGtmName: 'All-Season Floor Mat - 3rd Row',
    AccessoryNumber: '08P17-TYA-210A',
    AccessoryProvincialPrice: 138.3,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 3,
  },
];
