export default [
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307418_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307418_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307418_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307418_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24332_tall_windscreen',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'comfort',
      Name: 'Comfort',
      GtmName: 'Comfort',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Taller and wider than the standard windscreen, it provides added protection from the elements. 8.85” (225 mm) and 3.93” (100 mm)\nlonger than the Gold Wing and Gold Wing Tour windscreens respectively.\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24332,
    AccessoryIsResidualized: false,
    AccessoryKey: 'tall_windscreen',
    AccessoryListPrice: 408.95,
    AccessoryName: 'TALL WINDSCREEN',
    AccessoryGtmName: 'TALL WINDSCREEN',
    AccessoryNumber: '08R71-MKC-A01',
    AccessoryProvincialPrice: 408.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307419_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307419_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307419_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307419_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24333_air_deflector_a',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'comfort',
      Name: 'Comfort',
      GtmName: 'Comfort',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Specifically designed to improve comfort and match the styling of your motorcycle, the upper deflector provides the ability to direct airflow for various riding conditions.  \r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24333,
    AccessoryIsResidualized: false,
    AccessoryKey: 'air_deflector_a',
    AccessoryListPrice: 462.95,
    AccessoryName: 'AIR DEFLECTOR UPPER',
    AccessoryGtmName: 'AIR DEFLECTOR UPPER',
    AccessoryNumber: '08R72-MKC-A01',
    AccessoryProvincialPrice: 462.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307443_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307443_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307443_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307443_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24342_inner_bag_trunk',
    AccessoryCategory: {
      DisplayOrder: 23,
      Key: 'utility',
      Name: 'Utility',
      GtmName: 'Utility',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Convenient abrasion-resistant ballistic nylon trunk liner makes packing easier and protects your belongings when traveling.  Features reinforced carry handles, shoulder strap, easy-access outer zip for in-trunk use, and Gold Wing logo zipper pulls. Optional on Gold Wing models with the addition of the Trunk.',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24342,
    AccessoryIsResidualized: false,
    AccessoryKey: 'inner_bag_trunk',
    AccessoryListPrice: 169.95,
    AccessoryName: 'Inner Bag, Trunk',
    AccessoryGtmName: 'Inner Bag, Trunk',
    AccessoryNumber: '08L00-MKC-A00',
    AccessoryProvincialPrice: 169.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307445_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307445_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307445_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307445_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24344_rear_carrier',
    AccessoryCategory: {
      DisplayOrder: 23,
      Key: 'utility',
      Name: 'Utility',
      GtmName: 'Utility',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Adds style and functionality, featuring a black finish with rubber inserts for improved appearance while adding carrying capacity. Weight limit: 6.6 lb (3 kg.). Optional on Gold Wing Tour models with the Trunk Removed.',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24344,
    AccessoryIsResidualized: false,
    AccessoryKey: 'rear_carrier',
    AccessoryListPrice: 575.95,
    AccessoryName: 'Rear Carrier',
    AccessoryGtmName: 'Rear Carrier',
    AccessoryNumber: '08L70-MKC-C40',
    AccessoryProvincialPrice: 575.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307446_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307446_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307446_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307446_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24345_trunk_lid_organizer',
    AccessoryCategory: {
      DisplayOrder: 23,
      Key: 'utility',
      Name: 'Utility',
      GtmName: 'Utility',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Helps keep your trunk organized with convenient storage pockets for smaller items. Optional on Gold Wing models with the addition of the Trunk.',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24345,
    AccessoryIsResidualized: false,
    AccessoryKey: 'trunk_lid_organizer',
    AccessoryListPrice: 71.95,
    AccessoryName: 'Trunk Lid Organizer',
    AccessoryGtmName: 'Trunk Lid Organizer',
    AccessoryNumber: '08L78-MKC-A00',
    AccessoryProvincialPrice: 71.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307427_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307427_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307427_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307427_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24352_front_caliper_cover__chrome_',
    AccessoryCategory: {
      DisplayOrder: 22,
      Key: 'custom',
      Name: 'Custom',
      GtmName: 'Custom',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Chrome-plated, injection-molded ABS construction covers add custom styling and provides additional airflow to your front calipers for cooling.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24352,
    AccessoryIsResidualized: false,
    AccessoryKey: 'front_caliper_cover__chrome_',
    AccessoryListPrice: 543.95,
    AccessoryName: 'FRONT CALIPER COVER (CHROME)',
    AccessoryGtmName: 'FRONT CALIPER COVER (CHROME)',
    AccessoryNumber: '08F73-MKC-A00',
    AccessoryProvincialPrice: 543.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307436_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307436_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307436_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307436_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24357_illuminated_entry_lamp',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'lights',
      Name: 'Lights',
      GtmName: 'Lights',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: 'Improves visibility around motorcycle when parked with exterior area lighting.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24357,
    AccessoryIsResidualized: false,
    AccessoryKey: 'illuminated_entry_lamp',
    AccessoryListPrice: 201.95,
    AccessoryName: 'ILLUMINATED ENTRY LAMP',
    AccessoryGtmName: 'ILLUMINATED ENTRY LAMP',
    AccessoryNumber: '08U70-MKC-A00',
    AccessoryProvincialPrice: 201.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307431_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307431_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307431_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307431_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24362_homelink___attachment_kit',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'electrical',
      Name: 'Electrical',
      GtmName: 'Electrical',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Provides the convenience of operating two different garage openers from your motorcycle.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24362,
    AccessoryIsResidualized: false,
    AccessoryKey: 'homelink___attachment_kit',
    AccessoryListPrice: 340.95,
    AccessoryName: 'HOMELINK & ATTACHMENT KIT',
    AccessoryGtmName: 'HOMELINK & ATTACHMENT KIT',
    AccessoryNumber: '08U77-MKC-A00',
    AccessoryProvincialPrice: 340.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307414_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307414_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307414_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307414_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24363_pass_audio_switch___attachment',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'audio',
      Name: 'Audio',
      GtmName: 'Audio',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: 'Allows your passenger to adjust the volume, source and track. \r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24363,
    AccessoryIsResidualized: false,
    AccessoryKey: 'pass_audio_switch___attachment',
    AccessoryListPrice: 285.95,
    AccessoryName: 'PASS AUDIO SWITCH & ATTACHMENT',
    AccessoryGtmName: 'PASS AUDIO SWITCH & ATTACHMENT',
    AccessoryNumber: '08A70-MKC-A00',
    AccessoryProvincialPrice: 285.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307432_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307432_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307432_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307432_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24369_accessory_socket___attachment_kit',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'electrical',
      Name: 'Electrical',
      GtmName: 'Electrical',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription: '12V DC electrical socket provides power for additional electrical equipment.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24369,
    AccessoryIsResidualized: false,
    AccessoryKey: 'accessory_socket___attachment_kit',
    AccessoryListPrice: 58.95,
    AccessoryName: 'ACCESSORY SOCKET & ATTACHMENT KIT',
    AccessoryGtmName: 'ACCESSORY SOCKET & ATTACHMENT KIT',
    AccessoryNumber: '08U79-MKC-A00',
    AccessoryProvincialPrice: 58.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307417_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307417_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307417_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307417_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24372_speaker_rear_attachment',
    AccessoryCategory: {
      DisplayOrder: 0,
      Key: 'audio',
      Name: 'Audio',
      GtmName: 'Audio',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Includes speaker grilles, hardware and wiring for installation of two rear speakers on your Gold Wing.  Requires Rear Speaker Kit.\r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24372,
    AccessoryIsResidualized: false,
    AccessoryKey: 'speaker_rear_attachment',
    AccessoryListPrice: 342.95,
    AccessoryName: 'REAR SPEAKER ATTACHMENT',
    AccessoryGtmName: 'REAR SPEAKER ATTACHMENT',
    AccessoryNumber: '08B71-MKC-A00',
    AccessoryProvincialPrice: 342.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307451_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307451_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307451_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307451_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24380_motorcycle_cover_for_f6b',
    AccessoryCategory: {
      DisplayOrder: 21,
      Key: 'protection',
      Name: 'Protection',
      GtmName: 'Protection',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      'Sturdy, water resistant 300 denier helps protect your motorcycle from the elements.  Features a soft inner liner, venting, pop-out windshield panel, Gold Wing logos.  Includes storage bag.  \r\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24380,
    AccessoryIsResidualized: false,
    AccessoryKey: 'motorcycle_cover_for_f6b',
    AccessoryListPrice: 279.95,
    AccessoryName: 'MOTORCYCLE COVER',
    AccessoryGtmName: 'MOTORCYCLE COVER',
    AccessoryNumber: '08P71-MKC-A10',
    AccessoryProvincialPrice: 279.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307440_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307440_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307440_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307440_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24549_trunk_installation_kit',
    AccessoryCategory: {
      DisplayOrder: 20,
      Key: 'leather__bags',
      Name: 'Leather & Bags',
      GtmName: 'Leather & Bags',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      ' The Trunk installation kit provides the necessary hardware to install a trunk on the Gold Wing model. This kit includes the 55 W rear speakers that come factory on the Gold Wing Tour models . Requires a Rear Trunk Add kit.  \n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24549,
    AccessoryIsResidualized: false,
    AccessoryKey: 'trunk_installation_kit',
    AccessoryListPrice: 1385.95,
    AccessoryName: 'Trunk Installation Kit',
    AccessoryGtmName: 'Trunk Installation Kit',
    AccessoryNumber: '08L71-MKC-L31ZA',
    AccessoryProvincialPrice: 1385.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
  {
    TransmissionId: 11742,
    OverlayAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307442_ovr_off.jpg',
    ThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307442_thumbnail.jpg',
    ThumbnailColorAssetUrl: null,
    DefaultThumbnailAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/en_Default_thumbnail.jpg',
    FrontOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307442_ovr_front_on.png',
    FrontOnColorAssetUrl: null,
    BackOnAssetUrl: 'https://uat-staging-images.honda.ca:443/accessories/M/2023/307442_ovr_back_on.png',
    BackOnColorAssetUrl: null,
    AccessoryBusinessKey: '24551_trunk_mat',
    AccessoryCategory: {
      DisplayOrder: 20,
      Key: 'leather__bags',
      Name: 'Leather & Bags',
      GtmName: 'Leather & Bags',
    },
    AccessoryDefaultTireType: 'N',
    AccessoryDescription:
      ' Plush premium-quality carpeting with slip-resistant backing, embroidered with Gold Wing logo for your trunk. Optional on Gold Wing models with the addition of the Trunk\n',
    AccessoryDiscountPercent: 0.0,
    AccessoryFrt: 0.0,
    AccessoryId: 24551,
    AccessoryIsResidualized: false,
    AccessoryKey: 'trunk_mat',
    AccessoryListPrice: 130.95,
    AccessoryName: 'Trunk Mat',
    AccessoryGtmName: 'Trunk Mat',
    AccessoryNumber: '08P04-MKC-L00',
    AccessoryProvincialPrice: 130.95,
    AccessoryResidualAmount: 0.0,
    Dependencies: [],
    Exclusions: [],
    AccessoryDisplayOrder: 0,
  },
];
