export const fields = {
  items: [
    {
      fields: [
        {
          key: 'value 1',
        },
      ],
    },
    {
      fields: [
        {
          key: 'value 2',
        },
      ],
    },
    {
      fields: [
        {
          key: 'value 3',
        },
      ],
    },
  ],
};

export const componentObject = [
  {
    uid: 'd1001359-13aa-4874-9c2a-cb17b6631222',
    componentName: 'Header',
    dataSource: '{03A286D4-BBF1-425D-A6ED-FCA035950DDB}',
    params: {},
    items: [
      {
        itemId: '8d06a008-dd79-4fff-b5ec-5c09ede43b92',
        itemUrl: '/Global/Header/TopNavigation',
        itemName: 'TopNavigation',
        itemDisplayName: 'TopNavigation',
        items: [
          {
            itemId: '1c3dd3f4-f233-4934-bb02-d9421ebb33a4',
            itemUrl: '/Global/Header/TopNavigation/Engines',
            itemName: 'Engines',
            itemDisplayName: 'Engines',
            icon: '',
            image: {
              alt: 'sample image',
              class: 'scEmptyImage',
              src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
            },
            alignment: 'Left',
            label: 'Engines',
            url: {
              href: '',
            },
            ctaLink: {
              href: 'https://engine.honda.ca/compare',
              text: 'View all Engines',
              title: 'View all Engines',
              linktype: 'external',
              url: 'https://engine.honda.ca/compare',
              anchor: '',
              target: '',
            },
            ctaType: '',
            ctaIcon: null,
            ctaImage: {
              alt: 'sample image',
              class: 'scEmptyImage',
              src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
            },
            gtmInteractionType: '',
            gtmModelName: '',
            gtmTrimName: '',
            gtmBodyStyle: '',
            items: [
              {
                itemId: '6ea730b0-1d02-407a-8f71-5a0083d2b06c',
                itemUrl: '/Global/Header/TopNavigation/Engines/SubMenuCardItemSection',
                itemName: 'SubMenuCardItemSection',
                itemDisplayName: 'SubMenuCardItemSection',
                items: [
                  {
                    itemId: '12987060-a0c1-4b26-ae08-66d9049f7761',
                    itemUrl: '/Global/Header/TopNavigation/Engines/SubMenuCardItemSection/GX-Series',
                    itemName: 'GX Series',
                    itemDisplayName: 'GX Series',
                    image: {
                      alt: 'sample image',
                      height: '1131',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      title: 'Front of Honda GX100 engine (2nd image)',
                      width: '835',
                    },
                    description: 'Exceptional performance, quality and reliability, thats what you get from Honda.',
                    label: 'GX Series',
                    ctaIcon: null,
                    ctaLink: {
                      anchor: '',
                      href: 'https://engine.honda.ca',
                      linktype: 'external',
                      target: '',
                      text: 'Engine Homepage',
                      url: 'https://engine.honda.ca',
                    },
                    ctaType: '',
                    ctaImage: {
                      alt: 'sample image',
                      height: '1131',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      title: 'Front of Honda GX100 engine (2nd image)',
                      width: '835',
                    },
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '91d2840d-5f12-439f-a31a-00217b0312b0',
                    itemUrl: '/Global/Header/TopNavigation/Engines/SubMenuCardItemSection/Mini-4-Stroke-Series',
                    itemName: 'Mini 4-Stroke Series',
                    itemDisplayName: 'Mini 4-Stroke Series',
                    image: {
                      alt: 'sample image',
                      height: '729',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      width: '786',
                    },
                    description: '',
                    label: 'Mini 4-Stroke Series',
                    ctaLink: {
                      anchor: '',
                      href: 'https://engine.honda.ca',
                      linktype: 'external',
                      target: '',
                      text: 'Mini 4 Series',
                      title: 'Mini 4 Series',
                      url: 'https://engine.honda.ca',
                    },
                    ctaType: '',
                    ctaIcon: null,
                    ctaImage: {
                      alt: 'sample image',
                      height: '729',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      width: '786',
                    },
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '9a3bb5bd-05da-40ae-a34a-3d5b0bb68834',
                    itemUrl: '/Global/Header/TopNavigation/Engines/SubMenuCardItemSection/V-Twin-Series',
                    itemName: 'V-Twin Series',
                    itemDisplayName: 'V-Twin Series',
                    image: {
                      alt: 'sample image',
                      height: '594',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      width: '687',
                    },
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
                    label: 'V-Twin Series',
                    ctaLink: {
                      anchor: '',
                      href: 'https://engine-dit-01-dmm.engine.honda.ca',
                      linktype: 'external',
                      target: '',
                      text: 'Mini 4 Series',
                      title: 'Mini 4 Series',
                      url: 'https://engine-dit-01-dmm.engine.honda.ca',
                    },
                    ctaType: '',
                    ctaIcon: null,
                    ctaImage: {
                      alt: 'sample image',
                      height: '594',
                      src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
                      width: '687',
                    },
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                ],
              },
            ],
          },
          {
            itemId: 'cf748bf8-096b-4d3c-8165-2beb1a350e662',
            itemUrl: '/Global/Header/TopNavigation/Why-Honda',
            itemName: 'Why Honda',
            itemDisplayName: 'Why Honda',
            icon: {},
            image: {},
            alignment: 'Left',
            subMenuType: '',
            label: 'Why Honda?',
            url: {
              href: 'https://honda.ca',
              text: 'Why Honda',
              linktype: 'external',
              url: 'https://honda.ca',
              anchor: '',
              target: '_blank',
            },
            ctaLink: {
              href: '',
            },
            ctaType: '',
            ctaIcon: null,
            ctaImage: {},
            gtmInteractionType: '',
            gtmModelName: '',
            gtmTrimName: '',
            gtmBodyStyle: '',
          },
          {
            itemId: '65aeacde-728c-42df-8abb-2d53283395c3',
            itemUrl: '/Global/Header/TopNavigation/Service & Support',
            itemName: 'Service & Support',
            itemDisplayName: 'Service & Support',
            icon: {},
            image: {
              src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
              alt: 'sample image',
              width: '590',
              height: '360',
            },
            alignment: 'Left',
            subMenuType: 'SubMenuListItem',
            label: 'Service & Support',
            url: {
              href: '',
            },
            ctaLink: {
              href: 'https://honda.ca/Service&Support',
              text: 'View All Service & Support',
              linktype: 'external',
              url: 'https://honda.ca',
              anchor: '',
              target: '',
            },
            ctaType: 'Tertiary',
            ctaIcon: {
              itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a7224',
              itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
              itemName: 'Arrow-right',
              itemDisplayName: 'Arrow-right',
              value: 'arrowRight',
            },
            ctaImage: {},
            gtmInteractionType: '',
            gtmModelName: '',
            gtmTrimName: '',
            gtmBodyStyle: '',
            items: [
              {
                itemId: '9d872f90-df0d-45c5-a87f-42b0d67737f6',
                itemUrl: '/Global/Header/TopNavigation/Engines/SubMenuListItemSection',
                itemName: 'SubMenuListItemSection',
                itemDisplayName: 'SubMenuListItemSection',
                items: [
                  {
                    itemId: '61b4356b-a694-41ad-b469-019ecc2cd4df',
                    itemUrl: '/Global/Header/TopNavigation/Engines/Service & Warranty',
                    itemName: 'Service & Warranty',
                    itemDisplayName: 'Service & Warranty',
                    subMenuType: 'SubMenuListItem',
                    image: {},
                    description: '',
                    label: 'Service & Warranty',
                    url: {
                      href: '',
                    },
                    ctaLink: {
                      href: '',
                    },
                    ctaType: 'Tertiary',
                    ctaIcon: {
                      itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a722133',
                      itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
                      itemName: 'Arrow-right',
                      itemDisplayName: 'Arrow-right',
                      value: 'arrowRight',
                    },
                    ctaImage: {},
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '61b4356b-a694-41ad-b469-019ecc2cd4d111111',
                    itemUrl: '/Global/Header/TopNavigation/Engines/Owner’s Manuals',
                    itemName: 'Owner’s Manuals',
                    itemDisplayName: 'Owner’s Manuals',
                    subMenuType: 'SubMenuListItem',
                    image: {},
                    description: '',
                    label: 'Owner’s Manuals',
                    url: {
                      href: '',
                    },
                    ctaLink: {
                      href: '',
                    },
                    ctaType: 'Tertiary',
                    ctaIcon: {
                      itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a7222412',
                      itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
                      itemName: 'Arrow-right',
                      itemDisplayName: 'Arrow-right',
                      value: 'arrowRight',
                    },
                    ctaImage: {},
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '61b4356b-a694-41ad-b469-019ecc2cd4d21',
                    itemUrl: '/Global/Header/TopNavigation/Engines/Identify Your Engine',
                    itemName: 'Identify Your Engine',
                    itemDisplayName: 'Identify Your Engine',
                    subMenuType: 'SubMenuListItem',
                    image: {},
                    description: '',
                    label: 'Identify Your Engine',
                    url: {
                      href: '',
                    },
                    ctaLink: {
                      href: '',
                    },
                    ctaType: 'Tertiary',
                    ctaIcon: {
                      itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a7222532',
                      itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
                      itemName: 'Arrow-right',
                      itemDisplayName: 'Arrow-right',
                      value: 'arrowRight',
                    },
                    ctaImage: {},
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '61b4356b-a694-41ad-b469-019ecc2cd4d22',
                    itemUrl: '/Global/Header/TopNavigation/Engines/Recall & Product Update Lookup',
                    itemName: 'Recall & Product Update Lookup',
                    itemDisplayName: 'Recall & Product Update Lookup',
                    subMenuType: 'SubMenuListItem',
                    image: {},
                    description: '',
                    label: 'Recall & Product Update Lookup',
                    url: {
                      href: '',
                    },
                    ctaLink: {
                      href: '',
                    },
                    ctaType: 'Tertiary',
                    ctaIcon: {
                      itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a7222876',
                      itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
                      itemName: 'Arrow-right',
                      itemDisplayName: 'Arrow-right',
                      value: 'arrowRight',
                    },
                    ctaImage: {},
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                  {
                    itemId: '61b4356b-a694-41ad-b469-019ecc2cd4d23',
                    itemUrl: '/Global/Header/TopNavigation/Engines/Find a Distributor',
                    itemName: 'Find a Distributor',
                    itemDisplayName: 'Find a Distributor',
                    subMenuType: 'SubMenuListItem',
                    image: {},
                    description: '',
                    label: 'Find a Distributor',
                    url: {
                      href: '',
                    },
                    ctaLink: {
                      href: '',
                    },
                    ctaType: 'Tertiary',
                    ctaIcon: {
                      itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a72229328',
                      itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
                      itemName: 'Arrow-right',
                      itemDisplayName: 'Arrow-right',
                      value: 'arrowRight',
                    },
                    ctaImage: {},
                    gtmInteractionType: '',
                    gtmModelName: '',
                    gtmTrimName: '',
                    gtmBodyStyle: '',
                  },
                ],
              },
            ],
          },
          {
            itemId: 'cf748bf8-096b-4d3c-8165-2beb1a350e663',
            itemUrl: '/Global/Header/TopNavigation/Manufacturers',
            itemName: 'Manufacturers',
            itemDisplayName: 'Manufacturers',
            icon: {},
            image: {},
            alignment: 'Left',
            subMenuType: '',
            label: 'Manufacturers',
            url: {
              href: 'https://honda.ca',
              text: 'Manufacturers',
              linktype: 'external',
              url: 'https://honda.ca',
              anchor: '',
              target: '_blank',
            },
            ctaLink: {
              href: '',
            },
            ctaType: '',
            ctaIcon: null,
            ctaImage: {},
            gtmInteractionType: '',
            gtmModelName: '',
            gtmTrimName: '',
            gtmBodyStyle: '',
          },
          {
            itemId: 'cf748bf8-096b-4d3c-8165-2beb1a350e661',
            itemUrl: '/Global/Header/TopNavigation/Distributors',
            itemName: 'Distributors',
            itemDisplayName: 'Distributors',
            icon: {
              alt: 'MapMarker',
              height: '23',
              src: './sample-mock-data/media/img/engine-header/map-marker.png',
              width: '17',
            },
            image: {
              alt: 'sample image',
              class: 'scEmptyImage',
              src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
            },
            alignment: 'Right',
            label: 'Distributors',
            url: {
              href: 'https://engine.honda.ca/',
              text: 'Distributors',
              linktype: 'external',
              url: 'https://engine.honda.ca/',
              anchor: '',
              target: '',
            },
            ctaLink: {
              href: '',
            },
            ctaType: '',
            ctaIcon: {
              itemId: 'f4b5230a-25a0-4d2e-8b07-cb59dc1a7221444',
              itemUrl: '/sitecore/System/Foundation/common/CTA-Icons/Arrow-right',
              itemName: 'Arrow-right',
              itemDisplayName: 'Arrow-right',
              value: 'mapMarker',
            },
            ctaImage: {
              alt: 'sample image',
              class: 'scEmptyImage',
              src: './sample-mock-data/media/img/placeholders/placeholder-landscape.png',
            },
            gtmInteractionType: '',
            gtmModelName: '',
            gtmTrimName: '',
            gtmBodyStyle: '',
          },
        ],
      },
    ],
  },
  {
    uid: 'aa61ffb8-7220-4df4-aa8c-0a6f9abff222',
    componentName: 'SiteLogo',
    dataSource: '{A9BA3BCE-93E8-4DA5-9DD2-552987B8691D}',
    params: {},
    siteLogo: {
      src: './sample-mock-data/media/img/placeholders/logo-placeholder.png',
      alt: 'logo',
      width: '115',
      height: '37',
    },
    headerUrl: {
      href: 'http://instagram.com/hondamotoca',
      linktype: 'external',
      url: 'http://instagram.com/hondamotoca',
    },
  },
];
