import Accessories from './components/Accessories';
import Accordion from './components/Accordion';
import AccordionItem from './components/AccordionItem';
import AnchorContainer from './components/AnchorContainer';
import AppBanner from './components/AppBanner';
import AppCard from './components/AppCard';
import AppHero from './components/AppHero';
import Awards from './components/Awards';
import CarouselCardsContainer from './components/CarouselCardsContainer';
import CarouselHero from './components/CarouselHero';
import CarouselSlider from './components/CarouselSlider';
import CarouselWithModalContainer from './components/CarouselWithModalContainer';
import CollapsibleContainer from './components/CollapsibleContainer';
import ColorDisplay from './components/ColorDisplay';
import CompareProducts from './components/CompareProducts';
import CompareProductsDrawer from './components/CompareProductsDrawer';
import CompareTrimSpecifications from './components/CompareTrimSpecifications';
import ContactUs from './components/ContactUs';
import CtaCard from './components/CtaCard/CtaCard';
import DealerBanner from './components/DealerBanner';
import DealerLocatorModal from './components/DealerLocatorModal';
import DiagonalCard from './components/DiagonalCard';
import DiagonalCardContainer from './components/DiagonalCardContainer';
import DistributorCard from './components/DistributerCard';
import DividerLine from './components/DividerLine';
import DropdownFilterContainer from './components/DropdownFilterContainer';
import EngineDetailsCard from './components/EngineDetailsCard';
import EngineFeatures from './components/EngineFeatures';
import EngineSeries from './components/EngineSeries';
import EngineSpecifications from './components/EngineSpecifications';
import FAQ from './components/FAQ';
import FiveCellLayout from './components/FiveCellLayout';
import Footer from './components/Footer';
import FourColumnLayoutContainer from './components/FourColumnLayoutContainer';
import FreeFormText from './components/FreeFormText';
import FullWidthCard from './components/FullWidthCard';
import FutureVehicleCard from './components/FutureVehicleCard';
import Gallery from './components/Gallery';
import Header from './components/Header';
import Hero from './components/Hero';
import HoverCard from './components/HoverCard';
import Icon from './components/Icon';
import IconCard from './components/IconCard';
import Image from './components/Image';
import KeyFeatures from './components/KeyFeatures';
import LandingPageCard from './components/LandingPageCard';
import LandscapeBoxCard from './components/LandscapeBoxCard';
import LandscapeCard from './components/LandscapeCard';
import LayoutContainer from './components/LayoutContainer';
import LinkPackageCard from './components/LinkPackageCard';
import LocalInventoryStatus from './components/LocalInventoryStatus';
import MCFooter from './components/MCFooter';
import MarineCategory from './components/MarineCategory';
import MarineProductConfigurations from './components/MarineProductConfigurations';
import MarineProductDetailsCard from './components/MarineProductDetailsCard';
import MarineProductFeatures from './components/MarineProductFeatures';
import MarineProductSpecifications from './components/MarineProductSpecifications';
import ModelCard from './components/ModelCard';
import ModelCardGrid from './components/ModelCardGrid';
import ModelCardWithTrims from './components/ModelCardWithTrims';
import ModelFeatures from './components/ModelFeatures';
import ModelListFilters from './components/ModelListFilters';
import ModelPageNav from './components/ModelPageNav';
import ModelSelector from './components/ModelSelector';
import NsxModelCard from './components/NsxModelCard';
import OffersProvider from './components/OffersProvider';
import PackageCard from './components/PackageCard';
import Parallax from './components/Parallax';
import PartStream from './components/PartStream';
import PlanCard2 from './components/PlanCard2';
import PortraitCard from './components/PortraitCard';
import PreOrderBanner from './components/PreOrderBanner';
import ProgressBar from './components/ProgressBar';
import PromoBanner from './components/PromoBanner';
import QuickLink from './components/QuickLink';
import SectionContainer from './components/SectionContainer';
import SectionNavigation from './components/SectionNavigation';
import ShowcaseCard from './components/ShowcaseCard';
import SideNav from './components/SideNav';
import SideNavLayout from './components/SideNavLayout';
import SideNavScrollIndicator from './components/SideNavScrollIndicator';
import SidebarLayout from './components/SidebarLayout';
import SimilarProducts from './components/SimilarProducts';
import SimilarRecentlyViewedProducts from './components/SimilarRecentlyViewedProducts';
import Slider from './components/Slider';
import Tab from './components/Tab';
import Table from './components/Table';
import TableStyle2 from './components/TableStyle2';
import TabsContainer from './components/TabsContainer';
import ThreeCellLayout from './components/ThreeCellLayout';
import ThreeColumnLayout from './components/ThreeColumnLayout';
import Title from './components/Title';
import TrimCardGrid from './components/TrimCardGrid';
import TrimOverview from './components/TrimOverview';
import TrimPackages from './components/TrimPackages';
import TrimPayment from './components/TrimPayment';
import TrimSelector from './components/TrimSelector';
import TrimSpecifications from './components/TrimSpecifications';
import TwoCardUpLayout from './components/TwoCardUpLayout';
import UnOrderedList from './components/UnOrderedList';
import VehicleListFilters from './components/VehicleListFilters';
import VideoComponent from './components/VideoComponent';
import { LayoutContext } from './components/LayoutContext';
import { SixCellLayout } from './components/SixCellLayout';
import AvailableVehicles from './components/AvailableVehicles';
import LeadsCtas from './components/LeadsCtas';

const components = new Map();
components.set('Accessories', Accessories);
components.set('Accordion', Accordion);
components.set('AccordionItem', AccordionItem);
components.set('AnchorContainer', AnchorContainer);
components.set('AppBanner', AppBanner);
components.set('AppCard', AppCard);
components.set('AppHero', AppHero);
components.set('Awards', Awards);
components.set('CarouselCardsContainer', CarouselCardsContainer);
components.set('CarouselHero', CarouselHero);
components.set('CarouselSlider', CarouselSlider);
components.set('CarouselWithModalContainer', CarouselWithModalContainer);
components.set('CollapsibleContainer', CollapsibleContainer);
components.set('ColorDisplay', ColorDisplay);
components.set('CompareDrawer', CompareProductsDrawer);
components.set('CompareProducts', CompareProducts);
components.set('CompareTrimSpecifications', CompareTrimSpecifications);
components.set('ContactUs', ContactUs);
components.set('CtaCard', CtaCard);
components.set('DealerBanner', DealerBanner);
components.set('DealerLocatorModal', DealerLocatorModal);
components.set('DiagonalCard', DiagonalCard);
components.set('DiagonalCardContainer', DiagonalCardContainer);
components.set('DistributorCard', DistributorCard);
components.set('DividerLine', DividerLine);
components.set('DropdownFilterContainer', DropdownFilterContainer);
components.set('EngineDetailsCard', EngineDetailsCard);
components.set('EngineFeatures', EngineFeatures);
components.set('EngineSeries', EngineSeries);
components.set('EngineSpecifications', EngineSpecifications);
components.set('FAQ', FAQ);
components.set('FaqContent', FAQ); // In the MC JSS app, FAQ is named FaqContent
components.set('FiveCellLayout', FiveCellLayout);
components.set('FiveColumnLayout', LayoutContainer);
components.set('Footer', Footer);
components.set('FourColumnLayout', FourColumnLayoutContainer);
components.set('FourColumnLayoutContainer', FourColumnLayoutContainer);
components.set('FreeFormText', FreeFormText);
components.set('FullWidthCard', FullWidthCard);
components.set('FutureVehicleCard', FutureVehicleCard);
components.set('Gallery', Gallery);
components.set('Header', Header);
components.set('Hero', Hero);
components.set('HoverCard', HoverCard);
components.set('Icon', Icon);
components.set('IconCard', IconCard);
components.set('Image', Image);
components.set('KeyFeaturesHero', KeyFeatures);
components.set('LandingPageCard', LandingPageCard);
components.set('LandscapeBoxCard', LandscapeBoxCard);
components.set('LandscapeCard', LandscapeCard);
components.set('LayoutContainer', LayoutContainer);
components.set('LayoutContext', LayoutContext);
components.set('LinkPackageCard', LinkPackageCard);
components.set('MarineCategory', MarineCategory);
components.set('MarineCategoryWithProducts', ModelCardWithTrims);
components.set('MarineProductConfigurations', MarineProductConfigurations);
components.set('MarineProductDetailsCard', MarineProductDetailsCard);
components.set('MarineProductFeatures', MarineProductFeatures);
components.set('MarineProductSpecifications', MarineProductSpecifications);
components.set('MCFooter', MCFooter);
components.set('ModelCard2', ModelCard);
components.set('ModelCardGrid', ModelCardGrid);
components.set('ModelCardWithTrims', ModelCardWithTrims);
components.set('ModelFeatures', ModelFeatures);
components.set('ModelListFilters', ModelListFilters);
components.set('ModelPageNav', ModelPageNav);
components.set('ModelSelector', ModelSelector);
components.set('NsxModelCard', NsxModelCard);
components.set('OffersProvider', OffersProvider);
components.set('PackageCard', PackageCard);
components.set('Parallax', Parallax);
components.set('PartStream', PartStream);
components.set('PlanCard2', PlanCard2);
components.set('PortraitCard', PortraitCard);
components.set('PreOrderBanner', PreOrderBanner);
components.set('PromoBanner', PromoBanner);
components.set('QuickLink', QuickLink);
components.set('SectionContainer', SectionContainer);
components.set('SectionNavigation', SectionNavigation);
components.set('ShowcaseCard', ShowcaseCard);
components.set('SideNav', SideNav);
components.set('SideNavLayout', SideNavLayout);
components.set('SideNavScrollIndicator', SideNavScrollIndicator);
components.set('SimilarProducts', SimilarProducts);
components.set('SimilarRecentlyViewedProducts', SimilarRecentlyViewedProducts);
components.set('SingleColumnLayout', LayoutContainer);
components.set('SiteLogo', () => null); // to prevent 'missing JSS component' error
components.set('SixCellLayout', SixCellLayout);
components.set('Slider', Slider);
components.set('Tab', Tab);
components.set('Table', Table);
components.set('TableStyle2', TableStyle2);
components.set('TabsContainer', TabsContainer);
components.set('ThreeCellLayout', ThreeCellLayout);
components.set('ThreeColumnLayout', ThreeColumnLayout);
components.set('Title', Title);
components.set('TrimCardGrid', TrimCardGrid);
components.set('TrimOverview', TrimOverview);
components.set('TrimPackages', TrimPackages);
components.set('TrimSelector', TrimSelector);
components.set('TrimPayment', TrimPayment);
components.set('TrimSpecifications', TrimSpecifications);
components.set('TwoCardUpLayout', TwoCardUpLayout);
components.set('TwoColumnLayout', LayoutContainer);
components.set('UnOrderedList', UnOrderedList);
components.set('VehicleListFilter', VehicleListFilters);
components.set('VideoComponent', VideoComponent);
components.set('SidebarLayout', SidebarLayout);
components.set('ProgressBar', ProgressBar);
components.set('LocalInventoryStatus', LocalInventoryStatus);
components.set('AvailableVehicles', AvailableVehicles);
components.set('LeadsCtas', LeadsCtas);

export default function componentFactory(componentName) {
  return components.get(componentName);
}
